import ANIM__FadeInOutOnScroll from "@/components/anims/fadein.anim";
import Navbar from "@/components/layouts/navbar";
import { cn } from "@udecode/cn";
import Icon__ChevronFill from "./_utils/assets/chevron-fill";
import { Bebas_Neue } from "next/font/google";
import { client } from "@/lib/ApolloClient";
import { GET_POSTS_COUNT } from "@/lib/Quries";
import Pagination from "./_utils/components/Pagination";
import { Metadata } from "next";
import BlogGrid from "./_utils/components/BlogGrid";
import dynamic from "next/dynamic";
import { Filter } from "./_utils/components/Filter";


const bebas_neue = Bebas_Neue({
  weight: "400",
  style: "normal",
  subsets: ["latin", "latin-ext"],
});


export const metadata: Metadata = {
  title: "The Skipr Scoop",
  description: "Generated by create next app",
  keywords: "The Skipr Scoop",
  openGraph: {
    images: [
      {
        url: "https://w3mantra.com/skipr_wp/wp-content/uploads/2021/10/Group-1.png",
        width: 800,
        height: 600,
        alt: "Og Image Alt",
      },
    ],
  },
};

const Page = async ({searchParams}: any) => {  

    const resPostsCount: any = await client.request(GET_POSTS_COUNT);

    const postsCount = resPostsCount.posts.pageInfo.total;

 



  return (
    <div className="py-24 container space-y-20">
      <Navbar color="black" />
      <ANIM__FadeInOutOnScroll className="flex flex-col min-[600px]:flex-row items-start min-[600px]:items-center justify-between gap-4">
        <ANIM__FadeInOutOnScroll className="space-y-4">
          <h1
            className={cn(
              bebas_neue.className,
              "text-left leading-[50px] uppercase text-[58px] 2xl:text-[64px] text-[#001C2F]"
            )}
          >
            The Skipr
            <br />
            Scoop
          </h1>
          <p className="text-[#001C2F] font-[500]">
            The latest, the greatest and the stuf 
            <br /> you should really know.
          </p>
        </ANIM__FadeInOutOnScroll>
        <Filter />
      </ANIM__FadeInOutOnScroll>
      <BlogGrid postsCount={postsCount} />
    </div>
  );
};

export default dynamic(() => Promise.resolve(Page), { ssr: false });