import Navbar from "@/components/layouts/navbar";
import Section__HomeHero from "./_utils/components/hero.section";
import Section__Privacy from "./_utils/components/privacy.section";
import Section__Monitor from "./_utils/components/monitor.section";
import Section__Knowledge from "./_utils/components/knowledge.section";
import Section__Autonomy from "./_utils/components/autonomy.section";
import Section__Patent from "./_utils/components/patent.section";
import Section__Performance from "./_utils/components/performance.section";
import Section__Features from "./_utils/components/features.section";
import Section__Platforms from "./_utils/components/platforms.section";
import Section__FeaturesMess from "./_utils/components/features__mess.section";
import Section__Table from "./_utils/components/table.section";
import Section__Last from "./_utils/components/last.section";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "The Skipr Scoop",
  description: "Generated by create next app",
  keywords: "The Skipr Scoop",
  openGraph: {
    images: [
      {
        url: "https://w3mantra.com/skipr_wp/wp-content/uploads/2021/10/Group-1.png",
        width: 800,
        height: 600,
        alt: "Og Image Alt",
      },
    ],
  },
};

const Home = () => {
  return (
    <>
      <Navbar color="white" />
      <Section__HomeHero />
      <Section__Privacy />
      <Section__Monitor />
      <Section__Knowledge />
      <Section__Autonomy />
      <Section__Patent />
      <Section__Performance />
      <Section__Features />
      <Section__Platforms />
      <Section__FeaturesMess />
      <Section__Table />
      <Section__Last />
    </>
  );
};

export default Home;
